### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by wkzqn** [awslabs/iam-roles-anywhere-session#9]
botocore.exceptions.SSLError: SSL validation failed for https://rolesanywhere.us-east-1.amazonaws.com/sessions [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

**Comment by junhong-l** [comment]
you need endpoint="rolesanywhere.cn-northwest-1.amazonaws.com"

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。

**Comment by tbuatois** [comment]
Hello @wkzqn, 

I did not head back from your issue but the latest release 2.2.0 enables you to skip certificate validation if needed. 

Thomas.

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。
